name: Java CI with Maven

on:
  push:
    branches: [ "main" ] # Main branch එකට push කරාම වැඩ කරන්න
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # GitHub එකේ ලිනක්ස් මැෂින් එකක් ඉල්ලනවා

    steps:
      - uses: actions/checkout@v3 # 1. අපේ Code එක ගන්නවා

      - name: Set up JDK 21
        uses: actions/setup-java@v3 # 2. Java Install
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests # 3. Build කරනවා (දැනට Tests skip කරමු)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: banking-app-jar
          path: target/*.jar # 4. හැදුන JAR file එක save කරගන්නවා